---
log_file: .\scheduler_logs
log_level: debug

sql_user: postgres
sql_pass: postgres
sql_host: db
sql_port: 5432
db_name: gocalendar

rabbit_user: guest
rabbit_pass: guest
#rabbit_host: rabbitmq
rabbit_host: rabbit
rabbit_port: 5672